### ISSUE TITLE
PPO + LSTM issues

### ISSUE THREAD

**Issue by antoine-galataud** [facebookresearch/Pearl#29]
First of all, thank you for sharing this project in an open source form!

While testing PPO + LSTM, I've identified 2 potential improvements:

- LSTM historization module requires the next state of the trajectory to be available. `OnPolicyEpisodicReplayBuffer`, which is the one used in many examples with PPO, doesn't compute it by default. This leads to the following exception: 
  ```python
  Error
  Traceback (most recent call last):
    File "/home/antoine/git/Pearl/pearl/test/integration/integration_tests.py", line 389, in test_ppo_lstm
      target_return_is_reached(
    File "/home/antoine/git/Pearl/pearl/utils/functional_utils/train_and_eval/online_learning.py", line 192, in target_return_is_reached
      episode_info, episode_total_steps = run_episode(
    File "/home/antoine/git/Pearl/pearl/utils/functional_utils/train_and_eval/online_learning.py", line 275, in run_episode
      agent.learn()
    File "/home/antoine/git/Pearl/pearl/pearl_agent.py", line 205, in learn
      report = self.policy_learner.learn(self.replay_buffer)
    File "/home/antoine/git/Pearl/pearl/policy_learners/sequential_decision_making/ppo.py", line 154, in learn
      result = super().learn(replay_buffer)
    File "/home/antoine/git/Pearl/pearl/policy_learners/policy_learner.py", line 170, in learn
      batch = self.preprocess_batch(batch)
    File "/home/antoine/git/Pearl/pearl/policy_learners/policy_learner.py", line 188, in preprocess_batch
      batch.next_state = self._history_summarization_module(batch.next_state)
    File "/home/antoine/git/Pearl/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/home/antoine/git/Pearl/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/antoine/git/Pearl/pearl/history_summarization_modules/lstm_history_summarization_module.py", line 100, in forward
      batch_size = x.shape[0]
  AttributeError: 'NoneType' object has no attribute 'shape'
  ```
- Input `batch.state` is being modified by historization module in https://github.com/facebookresearch/Pearl/blob/dfd6095cbf54440c41144ec2fb3ba51497502af5/pearl/policy_learners/policy_learner.py#L186 and then it is reused in critic and actor losses computation, leading to the following exception: 
  ```python
  Error
  Traceback (most recent call last):
    File "/home/antoine/git/Pearl/pearl/test/integration/integration_tests.py", line 389, in test_ppo_lstm
      target_return_is_reached(
    File "/home/antoine/git/Pearl/pearl/utils/functional_utils/train_and_eval/online_learning.py", line 192, in target_return_is_reached
      episode_info, episode_total_steps = run_episode(
    File "/home/antoine/git/Pearl/pearl/utils/functional_utils/train_and_eval/online_learning.py", line 275, in run_episode
      agent.learn()
    File "/home/antoine/git/Pearl/pearl/pearl_agent.py", line 205, in learn
      report = self.policy_learner.learn(self.replay_buffer)
    File "/home/antoine/git/Pearl/pearl/policy_learners/sequential_decision_making/ppo.py", line 154, in learn
      result = super().learn(replay_buffer)
    File "/home/antoine/git/Pearl/pearl/policy_learners/policy_learner.py", line 171, in learn
      single_report = self.learn_batch(batch)
    File "/home/antoine/git/Pearl/pearl/policy_learners/sequential_decision_making/actor_critic_base.py", line 232, in learn_batch
      self._actor_learn_batch(batch)  # update actor
    File "/home/antoine/git/Pearl/pearl/policy_learners/sequential_decision_making/ppo.py", line 139, in _actor_learn_batch
      loss.backward()
    File "/home/antoine/git/Pearl/venv/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
      torch.autograd.backward(
    File "/home/antoine/git/Pearl/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
      Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
  ```

**Comment by BillMatrix** [comment]
Hi there, sorry about the late reply. We all just came back from our holiday breaks. 

I think the problem is that currently history summarization module assumes the next state is available so it kinda assumes a bootstrapping based solution. See here: https://github.com/facebookresearch/Pearl/blob/main/pearl/policy_learners/policy_learner.py#L187 

I'll ask the team to submit a diff to fix this. Should be quick. Thanks for letting us know.

**Comment by antoine-galataud** [comment]
Thanks @BillMatrix for the feedback. I have submitted a PR to help with that (#30), hope this helps.

**Comment by yiwan-rl** [comment]
Hi @antoine-galataud, thanks for identifying this issue and the PR. We would like to incorporate your PR but we have not heard from you about the code review. 

It turns out that this issue is also related to another issue https://github.com/facebookresearch/Pearl/issues/47. We decided to fix both issues in one commit (https://github.com/facebookresearch/Pearl/commit/74741482ea5c864ebe7c7c35c5cf1fa27d83ddaa).

Thanks again for your help!
